from utils import load_dict

MIN_GUESSES = 3
MIN_WORD_LENGTH = 3
DEFAULT_WORD_LENGTH = 5
DEFAULT_NUM_GUESSES = 6
DIFFICULTY_CHOICES = [1,2,3]
DEFAULT_DIFFICULTY = 2
MAX_GUESSES = 10
MAX_WORD_LENGTH = 10
FILENAME = "./words.txt"
WORDS = load_dict(FILENAME)